-- ClassroomScope — run-tracking tables for the pipeline coordinator
-- DRAFT for Task 6.3 (shared schema discussion). Not yet applied.
--
-- Column names and allowed values match backend/orchestrator
-- (models.py and stages.py). If the team changes anything here,
-- update those two files to match.
--
-- Changes since the original proposal:
--   * 'security' added as a stage (Collection -> Security -> Analysis -> Aggregation)
--   * 'stance' added as a stage (stance_results table exists in the schema)
--   * final stage is named 'aggregation' (proposal said 'aggregate')

create table if not exists public.pipeline_runs (
  id                 bigint generated by default as identity primary key,
  trigger_type       text        not null
                     check (trigger_type in ('manual', 'scheduled')),
  status             text        not null
                     check (status in ('running', 'completed', 'completed_with_errors', 'failed')),
  started_at         timestamptz not null default now(),
  finished_at        timestamptz,
  articles_collected integer,
  notes              text
);

create table if not exists public.pipeline_stage_runs (
  id            bigint generated by default as identity primary key,
  run_id        bigint      not null references public.pipeline_runs (id) on delete cascade,
  stage_name    text        not null
                check (stage_name in ('collection', 'security', 'sentiment', 'topic',
                                      'classification', 'stance', 'aggregation')),
  status        text        not null default 'pending'
                check (status in ('pending', 'running', 'succeeded', 'failed', 'skipped')),
  attempt       integer     not null default 0,
  error_detail  text,
  started_at    timestamptz,
  finished_at   timestamptz,
  unique (run_id, stage_name)
);

create index if not exists pipeline_stage_runs_run_id_idx
  on public.pipeline_stage_runs (run_id);

-- Row-level security: left to the security owner to decide. If RLS is
-- enabled on these tables, the backend (which writes run status) needs
-- a policy allowing it, or it must use the service-role key.

-- OPEN QUESTION (not applied): tie each analysis result to the run that
-- produced it, so results can be filtered by run and a failed run's
-- partial output can be cleaned up.
--
-- alter table public.sentiment_results      add column run_id bigint references public.pipeline_runs (id);
-- alter table public.topic_results          add column run_id bigint references public.pipeline_runs (id);
-- alter table public.classification_results add column run_id bigint references public.pipeline_runs (id);
-- alter table public.stance_results         add column run_id bigint references public.pipeline_runs (id);
